### ISSUE TITLE
faut-il mettre les issues ici ou dans fioi-recorder ?

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/fioi-editor2#10]
les issues du fioi-recorder sont-elles au bon endroit ? Est-ce qu'il vaut mieux les mettre ici dans l'éditeur ?

Les issues en question:
https://github.com/France-ioi/fioi-recorder/issues

**Comment by epixode** [comment]
Les issues codecast sont au bon endroit dans France-ioi/fioi-recorder.

Ce repository (France-ioi/fioi-editor2) est une ancienne base de code contenant uniquement l'éditeur et l'enregistrement des évènements ciblant l'éditeur (et utilisant angular.js, alors que codecast est basé sur React).
